name: Publicar GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Enviar arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Publicar
        uses: actions/deploy-pages@v4
